id: P009129
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:24:26.334734
source_metadata:
  id: bdr:W1KG20637
  title: མདོ་སྨད་གཡོན་རུའི་ལོ་རྒྱུས།
  author: ''
  volumes:
    d944184981b54613b3be030d1ca28c7e:
      image_group_id: I1KG20756
      title: ''
      volume_number: 1
      total_pages: 818
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
