id: I1D40E558
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:39:06+00:00'
last_modified: '2022-06-08T08:49:51.326350+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG20637
  title: མདོ་སྨད་གཡོན་རུའི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    CC8F:
      image_group_id: I1KG20756
      title: ''
      total_pages: 818
      order: 1
      base_file: CC8F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
